name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519  # Preserve formatting
          chmod 600 ~/.ssh/id_ed25519  # Set correct permissions
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh -v -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "echo 'SSH Connection Successful'"

      - name: Install Docker Compose (if missing)
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            if ! command -v docker-compose &> /dev/null; then
              curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            fi
          EOF

      - name: Deploy to DigitalOcean Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /root/oneshop-api  # Change to correct project directory
            git pull origin master  # Pull latest changes
            docker-compose down  # Stop running containers
            docker-compose up -d --build  # Restart FastAPI
          EOF
