name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Add environment variables if needed
    environment: production
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts
        # Ensure SSH key is cleaned up after use
        shell: bash

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean Server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            set -e  # Exit on any error
            cd /root/oneshop-api || exit 1  # Fail if directory doesn't exist
            git fetch --all
            git reset --hard origin/master  # Ensure clean state
            docker-compose down || true  # Continue even if this fails
            docker-compose up -d --build --remove-orphans  # Build and run
            docker system prune -f  # Clean up unused images
          EOF

      # Optional: Add cleanup step
      - name: Cleanup
        if: always()  # Run even if previous steps fail
        run: |
          rm -f ~/.ssh/id_ed25519