name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts 2>/dev/null || echo "SSH keyscan failed, proceeding anyway"
        shell: bash

      - name: Deploy to DigitalOcean Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /root/oneshop-api || exit 1
            
            # Install Docker and Compose
            if ! command -v docker >/dev/null 2>&1; then
              apt-get update
              apt-get install -y docker.io
              systemctl enable docker
              systemctl start docker
            fi
            if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
              apt-get install -y docker-compose-plugin || \
              (curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
               chmod +x /usr/local/bin/docker-compose)
            fi
            
            git fetch --all
            git reset --hard origin/main
            
            # Ensure docker-compose.yml is in the right directory
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found"
              exit 1
            fi
            
            if docker compose version >/dev/null 2>&1; then
              docker compose down || true
              docker compose up -d --build --remove-orphans
            else
              docker-compose down || true
              docker-compose up -d --build --remove-orphans
            fi
            
            docker system prune -f
          EOF

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519